name: brent-oil-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  - statsmodels>=0.13.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter
  - pytest
  - flake8